#!/usr/bin/env bash
#this script is displaying "Best School" 10 times using while loop
#initialize counter
counter=0
#use while to display best school 10 times
while [ $counter -lt 10 ]; do
echo "Best School"
((counter++))
done
