#!/usr/bin/env bash
# This script displays numbers from 1 to 20 with specific messages using a while loop and a case statement

# Initialize counter
counter=1

# Use while loop to iterate from 1 to 20
while [ $counter -le 20 ]; do
    case $counter in
        "4")
            echo "bad luck from China"
            ;;
        "9")
            echo "bad luck from Japan"
            ;;
        "17")
            echo "bad luck from Italy"
            ;
    esac

    ((counter++))
done
