#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes using a while loop
#display hours from 0-12
#display minutes from1-59
hour=0
while [ $hour -le 12 ]; do
	echo "hour:$hour"
	minute=1
	while [$minute -le 59 ]; do
		echo "minute$minute"
		(( minute++ ))
	done
	(( hour++ ))
done
