#!/usr/bin/env bash
# This script displays the content of the current directory in a list format
# Only the part of the name after the first dash is displayed

# Use for loop to iterate through files in the current directory
for file in *; do
    # Check if the file is not hidden
    if [[ ! $file == .* ]]; then
        # Extract the part after the first dash in the file name
        name_part=$(echo "$file" | cut -d'-' -f2-)

        # Display the formatted list
        echo "$name_part"
    fi
done
