#!/usr/bin/env bash

pid_file="/var/run/myscript.pid"

# Function to clean up and exit
cleanup() {
    echo "Deleting $pid_file and terminating the script."
    rm -f "$pid_file"
    exit
}

# Trap signals and call the cleanup function
trap 'cleanup' SIGQUIT SIGTERM

# Trap SIGTERM signal to display a message
trap 'echo "I hate the kill command"' SIGTERM

# Trap SIGINT signal to display a message
trap 'echo "Y U no love me?!"' SIGINT

# Create the PID file
echo $$ > "$pid_file"
echo "To infinity and beyond"

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 1
done
